content: 
  version: 3.6
  command: pet
  probability: 30
  antialias: true
  disabled: []
  keyCommand: true
  keyCommandHead: ''
  commandMustAt: false
  respondImage: true
  respondSelfNudge: false
  fuzzy: false
  headless: true
  autoUpdate: true